name: BusinessWorld
version: 1.3
author: Poke_Diamond
main: fr.pokediamond.businessworld.Main
commands:
  test:
    description: Ceci est une commande de test
    permission: test.use
  alert:
    description: Ceci est un broadcast custom
    permission: bc.use
  mine:
    description: Cette commande permet de se tp a la mine de votre choix
  village:
    description: Cette commande permet de se tp au village et d arreter la facture de la mine dans laquel vous etes
  moneygivechrono:
    description: Cette commande permet d enclencher le give de money toutes les 10 minutes
    